### PR TITLE
fix: compilation errors, typo in GCS provisioner, IAM client delete account

### LINKED ISSUE #54: Deprovisioning of service account fails
# Bug Report

## Describe the Bug
Requesting the deprovisioning of service account created during provisioning fails with "com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Failed to parse resource name ", the service account is not deleted.

## Context Information
EDC 0.3.1

## Possible Implementation

Verify the IAM client implementation and fix the deleteServiceAccountIfExists method.

### PR DESCRIPTION
**Pull request by man8pr**
## What this PR changes/adds

- with 0.3.2 pipeline.DataSource needs to implement AutoCloseable, added close method to GCS data source
- typo in GCS provisioner copying email address onto service account name
- improved deleteServiceAccountIfExists method of IamServiceImpl following https://cloud.google.com/java/docs/reference/google-iam-admin/1.2.3/com.google.cloud.iam.admin.v1.IAMClient#com_google_cloud_iam_admin_v1_IAMClient_deleteServiceAccount_java_lang_String_
- changed rootProject.name to be case sensitive to avoid "IllegalStateException: Module entity with name: Technology-Gcp.extensions.test should be available" while gradle sync

## Why it does that

Fixes deprovisioning of service accounts, and enable compilation with Connector 0.3.2

## Linked Issue(s)

Closes #54

### CODE REVIEW

File: extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/IamServiceImpl.java [hunk 1]
```diff
@@ -116,7 +116,8 @@ public GcpAccessToken createAccessToken(GcpServiceAccount serviceAccount) {
     @Override
     public void deleteServiceAccountIfExists(GcpServiceAccount serviceAccount) {
         try (var client = iamClientSupplier.get()) {
-            client.deleteServiceAccount(serviceAccount.getName());
+            ServiceAccountName serviceAccountName = ServiceAccountName.of(gcpProjectId, serviceAccount.getEmail());
```
Comment (paullatzelsperger) [inline extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/iam/IamServiceImpl.java:119]:
```suggestion
            var serviceAccountName = ServiceAccountName.of(gcpProjectId, serviceAccount.getEmail());
```

**Review by paullatzelsperger — COMMENTED** [review]
pls use var, looks good otherwise
